meta_product_name: "ukrAID"
meta_title: "ukrAID - Stand with Ukraine"
meta_description: "ukrAID utilizes user-aggregated data on aid services for Ukrainian refugees & provides them on a single easy-to-use & searchable page. In addition, ukrAID offers a collection of tips & tricks on how people from all over the world can help."
meta_image: "thumbnail.jpg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
